Add CLI support and made a configuration specification
dema-trading-ai/engine pull request #119
Opened 2021-03-26 19:10 UTC by pvdklei

# Fixes

Fixes #69

# What has been changed?

You can now change certain (stoploss, strategy and starting capital, but can be very easily changed) config parameters through the CLI. I also changed the configuration to be based on a specification so we can easily add new parameters: name, what type they should be, if they should be cli configurable, what the possible inputs are, minimum/maximum values. 

# Examples

`$docker run dema-engine:alpha main.py --help`

```
usage: main.py [-h] [-cap STARTING_CAPITAL] [-sl STOPLOSS] [-s STRATEGY_NAME]

Dema Trading Engine

optional arguments:
  -h, --help            show this help message and exit
  -cap STARTING_CAPITAL, --starting-capital STARTING_CAPITAL
  -sl STOPLOSS, --stoploss STOPLOSS
  -s STRATEGY_NAME, --strategy-name STRATEGY_NAME
```

`$docker run dema-engine:alpha main.py -cap -100`
`[CONFIG ERROR] starting-capital = -100.0 is under the minimum value 1.0`

# Actions to be performed before this can be merged

- [ ] PR depends on #
- [ ] Script to be run

# Security Measures

# Potential Issues/Future considerations

# Additional Info

2021-03-30 10:34 UTC, dema-trading-ai commented
@pvdklei could you maybe fix conflicting files?

2021-03-30 10:37 UTC, dema-trading-ai approved these changes

2021-03-30 10:37 UTC, dema-trading-ai commented on config/validations.py
> -            config[param] = default_value
How did you replace this?

2021-03-30 10:37 UTC, dema-trading-ai commented on config/validations.py
> +        assert_min_max(config, param_spec)
Ah I see, you moved it here. Perfect dude, really nice

2021-04-01 20:39 UTC, keebrev approved these changes

2021-04-02 09:17 UTC, pvdklei commented
automatic tests give error on `pip install ...`. Works fine on my computer, but takes very long, maybe thats it. Should I just merge?

2021-04-02 15:19 UTC, keebrev commented
@pvdklei can you fix codacy issues?

2021-04-02 16:10 UTC, dema-trading-ai requested changes
@pvdklei When I use '0.5' as SL value, I get an 'config error' which shouldn't be there. Please fix before this can be merged

2021-04-03 22:19 UTC, pvdklei commented
@dema-trading-ai the stoploss in `config.json` was set at -0.5, so thought a negative value was requested and put the maximum allowed value 0. Do we want it to be positive or negative? We could also allow both, but then we should convert it to the same value in the config validation. 

@keebrev the codacy issues are unused imports in a `__init__.py` file, but thats just for convenient importing (e.g, you don't have to do `from config.validations import validate` but `from config import validate`). I can resolve it if you'd like but I suggest we just ignore those warnings.

2021-04-04 07:31 UTC, keebrev commented
@pvdklei  Ah alright, do not really mind. But if it's possible we should allow both. Anyway; the error I got is nog concerning negative of positive number, the error says I cannot use a Float as SL..

2021-04-04 12:04 UTC, pvdklei commented
@keebrev I cant replicate your bug, but I think it might be because I removed all the quotes ("...") around the numbers in the config file. So `"stoploss": -0.5` instead of `"stoploss": "-0.5". That way it is automatically casted to the right type and seems far more logical to me. I also swapped out `"backtesting-till-now": "False"` for `"backtesting-till-now": false`.

2021-04-06 16:27 UTC, dema-trading-ai commented
@pvdklei I am sorry, I think I used a wrong image for trying... Seems to work perfectly...

2021-04-14 10:59 UTC, noudcorten commented on config/specification.json
> +    "options": ["1m", "5m", "1h"],
@pvdklei Why don't we support more options? e.g. 15m is used quite often as well right?

2021-04-14 11:20 UTC, noudcorten commented on config/specification.json
> +]
@pvdklei Is it possible to add an extra option based on PR #146 ? Once this PR is merged, we need to have the option 'stoploss-type' included. It has to handle the options stated in the PR description.

@dema-trading-ai @keebrev Do we want to wait with merging this PR before #146 is merged? What do you think?

2021-04-14 11:20 UTC, noudcorten commented on config/cli.py
> +import argparse
@pvdklei Do we need to update requirements.txt to be able to handle argparse?

2021-04-14 13:01 UTC, pvdklei commented on config/specification.json
> +    "options": ["1m", "5m", "1h"],
I thought the exchange had limited options, but I now see that we handle this with a regex and any value is possible. So I'll remove the options for now. I guess I can also add a regex entry in the spec.

2021-04-14 13:06 UTC, pvdklei commented on config/specification.json
> +]
It's as easy a adding

```
[
  ..., 
  {
    "name": "stoploss-type",
    "type": "string",
    "options": ["dynamic", "standard", "trailing"]
  },
  ...
]
```

to the spec, and then it will do some basic type and options validation. Think that it's best if this change is made in #146 itself.

2021-04-14 13:06 UTC, pvdklei commented on config/cli.py
> +import argparse
No! `argparse` is in the python std

2021-04-14 13:31 UTC, noudcorten approved these changes

2021-04-14 13:31 UTC, noudcorten commented on config/cli.py
> +import argparse
Ok! Nice :)

2021-04-14 13:31 UTC, noudcorten commented on config/specification.json
> +]
Yes agreed. I will change it.

2021-04-15 12:32 UTC, pvdklei commented
@dema-trading-ai There is still an outdated 'changes requested', that's solved right? Then we can finally merge :)

2021-04-16 08:29 UTC, merged