[Hotfix] Correct drawdown period
dema-trading-ai/engine pull request #180
Opened 2021-04-30 15:27 UTC by noudcorten

# Results of merging this

Fixes #173

# What has been changed?

* Correct drawdown period
* Added 'drawdown_at' to results overview

# Examples

N/A

# Actions to be performed before this can be merged

- [ ] PR depends on #
- [ ] Script to be run

# Security Measures

N/A

# Potential Issues / Future considerations

N/A

# Assumptions made / Things to add to the wiki
 
N/A

# Additional Info

N/A

2021-05-04 09:01 UTC, sheridavandenbent requested changes
Looks great!
One thing to think about - with the addition of 'max seen drawdown at', it isn't directly clear from one glance what the difference between the statistic 'max seen drawdown at' and the statistics 'max seen drawdown to & from' are. Maybe we should change those to 'max seen drawdown **period** to & from'?

2021-05-13 12:39 UTC, keebrev approved these changes

2021-05-14 07:19 UTC, keebrev commented on .github/workflows/deploy_to_stable.yml
> +          tags: dematrading/engine:stable, dematrading/engine:latest, dematrading/engine:${{ needs.generate-new-tag.outputs.new_tag }}  # Builds a package with the `stable` tag, and another with the
```suggestion
          tags: dematrading/engine:stable, dematrading/engine:${{ needs.generate-new-tag.outputs.new_tag }}  # Builds a package with the `stable` tag, and another with the version as tag.
```

Removed 'dematrading/engine:latest' from tags

2021-05-14 11:57 UTC, sheridavandenbent approved these changes

2021-05-14 15:04 UTC, merged