Fix a bug in the results when no trades are made
dema-trading-ai/engine pull request #182
Opened 2021-05-01 20:54 UTC by WillemGerritzen

# Results of merging this

Fixes #181

# What has been changed?

Added a check when the number of trades made is required that returns 1 if the variable == 0. On each instance of the usage, the variable is the denominator in a division.

# Examples

N/A

# Actions to be performed before this can be merged

N/A

# Security Measures

This is exception handling in and of itself.

# Potential Issues / Future considerations

Might need to keep in mind if we change the way results are displayed. Otherwise nothing critical

# Assumptions made / Things to add to the wiki
 
N/A

# Additional Info

2021-05-02 18:10 UTC, noudcorten reviewed
Good find! If no trades are made, the current placeholder value is now '1'. Maybe change this to '0' for cum_profit_percentage and to '-' for total_duration for a more logical backtest result.

2021-05-04 09:24 UTC, sheridavandenbent requested changes
I agree with @noudcorten! Should be changed to '0' and '-' respectively. Otherwise, great catch!

2021-05-06 14:24 UTC, WillemGerritzen commented
Done! Thanks for the feedback :)

2021-05-12 09:02 UTC, noudcorten commented on backtesting/results.py
> +                        round(c.cum_profit_percentage / (c.n_trades if c.n_trades > 0 else 1), 2),
As mentioned before, I would change the 'else 1' to 'else 0' here.

2021-05-13 12:40 UTC, keebrev commented on backtesting/results.py
> +                        round(c.cum_profit_percentage / (c.n_trades if c.n_trades > 0 else 1), 2),
@WillemGerritzen could you change this?

2021-05-13 13:42 UTC, geordle commented on backtesting/results.py
> +                        round(c.cum_profit_percentage / (c.n_trades if c.n_trades > 0 else 1), 2),
Hi Guys, just joining in. I just wanted to draw your attention to this cool github feature.  
```suggestion
                        round((c.cum_profit_percentage / c.n_trades) if c.n_trades > 0 else 0, 2),
```

2021-05-14 12:07 UTC, sheridavandenbent approved these changes

2021-05-14 12:09 UTC, keebrev approved these changes

2021-05-14 12:09 UTC, merged