Fix/metric tests
dema-trading-ai/engine pull request #238
Opened 2021-05-25 13:32 UTC by sheridavandenbent

# Results of merging this

Creates more tests for realised drawdown, and incorporates tests for worst/best trade, and marketchanges. Code by @noudcorten .

# What has been changed?

# Examples

# Actions to be performed before this can be merged

# Security Measures

# Potential Issues / Future considerations

# Assumptions made / Things to add to the wiki
 

# Additional Info

2021-05-25 13:49 UTC, sheridavandenbent commented on cli/checks/latest_version.py
> +from urllib.error import URLError
Why is this changed? What does it fix?

2021-05-25 13:49 UTC, sheridavandenbent commented on cli/checks/latest_version.py
> +from urllib.error import URLError
@noudcorten

2021-05-25 14:53 UTC, geordle requested changes

2021-05-25 14:53 UTC, geordle commented on modules/stats/stats.py
> +        open_trade_res = generate_open_trades_results(trading_module.open_trades)
I believe arg `closed_trades` passed here is only used in `generate_coin_results` for calling `self.calculate_statistics_per_coin`. Maybe lift that call  here. Saves you returning `best_worst_trade`

2021-05-25 14:53 UTC, geordle commented on modules/output/results.py
> +    worst_trade: float
```suggestion
    worst_trade_profit_percentage: float
```

2021-05-25 14:53 UTC, geordle commented on modules/stats/stats.py
Split `best_worst_trade` into 2 vars

2021-05-25 14:53 UTC, geordle commented on modules/stats/stats.py
> +
Think this is unrelated to the rest, iterating 2 times isn't that bad if it improves readability. I'd move this to a seperate method

2021-05-25 14:53 UTC, geordle commented on test/stats/test_coin_insights.py
> +    """Given only winning trades, 'worst trade' should be worst of all trades"""
```suggestion
    """Given only winning trades, 'best_trade' should be best of all trades"""
```

2021-05-25 14:53 UTC, geordle commented on test/stats/test_coin_insights.py
> +    """Given only winning trades, 'worst trade' should be worst of all trades"""
@sheridavandenbent please look at comments

2021-05-25 14:53 UTC, geordle commented on test/stats/test_coin_insights.py
> +
This is a bit hard to follow. Maybe simplify case/state a bit so it's easier to follow (FI: just 2 entries, multiply by 2 )

2021-05-25 14:53 UTC, geordle commented on test/stats/test_main_results.py
> +def test_trailing_stoploss():
I don't think this fully covers `trailing_stoploss`. I'd add a `buy => Rise => Low`

2021-05-25 15:39 UTC, sheridavandenbent commented on modules/output/results.py
> +    best_trade: float
Has been changed! Closing conversation

2021-05-27 08:39 UTC, sheridavandenbent commented on modules/stats/stats.py
> +        open_trade_res = generate_open_trades_results(trading_module.open_trades)
Done in recent commit! Closing conversation

2021-05-27 08:48 UTC, sheridavandenbent commented on modules/stats/stats.py
Resolved in recent commit, closing conversation

2021-05-27 08:59 UTC, sheridavandenbent commented on modules/stats/stats.py
> +
Have used the max function! Committed and pushed. Closing conversation!

2021-05-27 09:07 UTC, sheridavandenbent commented on test/stats/test_coin_insights.py
> +    """Given only winning trades, 'worst trade' should be worst of all trades"""
Comments are fixed, closing conversation

2021-05-27 09:08 UTC, sheridavandenbent commented on modules/setup/config/__init__.py
> -        begin_data = self.exchange.fetch_ohlcv(symbol='BTC/USDT', timeframe='1m', since=self.backtesting_from, limit=1)
@noudcorten well done, tagging you here so you'll see this! :)
Resolving conversation to allow merging

2021-05-27 12:26 UTC, geordle approved these changes

2021-05-27 12:28 UTC, merged