[Fix] Max seen dd
dema-trading-ai/engine pull request #251
Opened 2021-06-03 10:31 UTC by noudcorten

# Results of merging this

Fixes #

# What has been changed?

* Max seen drawdown calculation based on difference from candle 'open' to candle 'low'
* Changed handling of ROI and stoploss occuring in same candle
* Added more max seen dd tests

# Examples

# Actions to be performed before this can be merged

- [ ] PR depends on #
- [ ] Script to be run

# Security Measures

# Potential Issues / Future considerations

# Assumptions made / Things to add to the wiki
 

# Packages added

# Additional Info

2021-06-10 12:50 UTC, DemianVoorhagen6 requested changes
Lets go over the comments f2f after you read everything, I think we could improve some more.

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/stats.py
> +            total_value_low = get_total_value_at_tick(timestamp_value_low, timestamp_budget, tick)
The function 'get_total_value_at_tick' seems overly complicated, maybe we can refactor it? It takes 3 inputs, returns 3 outputs right away, direct use might even be easier(?)

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/stats.py
>                      max_seen_drawdown['drawdown'] = temp_seen_drawdown['drawdown']
```suggestion
                    max_seen_drawdown = temp_seen_drawdown
```
Not 100% sure this works but believe it does (and all lines beneath can be removed)

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/stats.py
> +            if total_value_low < temp_seen_drawdown['bottom']:
Shouldn't the new bottom be lower? So > becomes <?

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/trade.py
> +        self.current = ohlcv['close']
Why are .open and .current both referring to close?

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/trade.py
> +        if self.capital < self.temp_lowest_seen_capital:
Why does the variable contain temp? Shouldn't it be current?

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/trade.py
> +            if seen_drawdown < self.max_seen_drawdown:
Shouldn't this be the other way around too? Not sure, fact checking

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/trade.py
> +            self.low_value = ohlcv['low']
low_value is ambiguous imo, candle_low would be more suitable if you want to store the candle low. Value is too broad

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/trade.py
> +            self.open_value = ohlcv['open']
Same as above

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/trade.py
> +        if curr_open_capital > self.temp_highest_seen_capital:
```suggestion
        if curr_open_capital > self.temp_highest_seen_capital:
```
        if curr_total_capital > self.temp_highest_seen_capital:
Open suggests only open positions, total capital/balance/total would be more appropriate

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/trade.py
> +
I've seen this kind of implementation a lot in this PR, maybe make a function/one-liner to do this. Would save tens of lines in these files already.

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/tradingmodule.py
> +            self.total_fee_amount -= first_fee
```suggestion
            self.total_fee_amount -= first_fee
```
            self.total_fee_paid -= first_fee

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/tradingmodule.py
> +            # Reset trade stats
Does this cover the un-do of the trade on all levels? (Portfolio, coins, trade level)
Does .remove(trade) also reduce the amount of trades shown at the end?

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/tradingmodule.py
>          profit_percentage = ((ohlcv['high'] / trade.open) - 1.) * 100
The roi isn't necessarily 'high'?

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/tradingmodule.py
> +            self.open_trades_open_per_timestamp[ohlcv['time']] = \
Feels a bit though to read, no concrete solution comes to mind though

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/tradingmodule.py
> +            curr_low_capital = trade.low_value * trade.currency_amount
```suggestion
            curr_low_capital = trade.low_value * trade.currency_amount
```
Is low value for the lowest value? If so trough would be more meaningfull, e.g.:
curr_low_capital = trade.trough_value * trade.currency_amount
If this also applies for trough capital:
curr_trough_capital = trade.trough_value * trade.currency_amount

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on modules/stats/tradingmodule.py
> +            self.open_trades_low_per_timestamp[ohlcv['time']] = \
open_trades_low_per_timestamp is multi interpretable

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on test/stats/test_coin_insights.py
> +    of the combined trades"""
Can you brief me on this one?

2021-06-10 12:50 UTC, DemianVoorhagen6 commented on test/stats/test_roi_stoploss.py
> +    """Given 'value of coin falls below stoploss', 'profit' should 'lower same minus fee'"""
should be

2021-06-11 12:01 UTC, sheridavandenbent commented on modules/stats/tradingmodule.py
> +        """
```suggestion
```

Remove all unneccesary comments!

2021-06-11 14:29 UTC, sheridavandenbent commented on modules/stats/trade.py
> +        """
```suggestion
```

Unnecessary comment!

2021-06-11 14:30 UTC, sheridavandenbent commented on modules/stats/trade.py
> +        :rtype: None
```suggestion
```

Unnecessary comments

2021-06-11 14:31 UTC, sheridavandenbent approved these changes

2021-06-15 09:51 UTC, DemianVoorhagen6 submitted a review, later dismissed
Better :) I did notice new/other variable ambiguities, so let's be extra watchful on those to make sure we maintain high code quality and keep the project scalable.

2021-06-15 11:24 UTC, sheridavandenbent approved these changes

2021-06-15 11:24 UTC, merged