Adds config file location via CLI support
dema-trading-ai/engine pull request #254
Opened 2021-06-04 14:37 UTC by marijn111

# Results of merging this

Fixes #253 

# What has been changed?

@geordle made some changes enabling you to add the config file location as a flag via CLI.

# Examples

`docker-compose run --rm dema-engine -c custom_config.json`

# Actions to be performed before this can be merged

# Security Measures

In case of a non-existing file, the user is notified accordingly. Furthermore the default (`config.json`) remains, so that everything also works when not using the flag.

# Potential Issues / Future considerations

N/A

# Assumptions made / Things to add to the wiki
 
This expansion of the CLI should be added to the wiki

# Packages added

N/A

# Additional Info

N/A

2021-06-04 14:39 UTC, geordle submitted a review, later dismissed

2021-06-04 19:22 UTC, geordle commented
Hya, just noticed this PR is for a merge into main. Could you set target to develop?

2021-06-05 06:50 UTC, geordle requested changes
Change target main => develop

2021-06-06 13:38 UTC, marijn111 commented
@geordle, Thanks!

2021-06-06 13:58 UTC, geordle approved these changes

2021-06-07 10:09 UTC, merged