Fix/max seen drawdown simple
dema-trading-ai/engine pull request #280
Opened 2021-06-17 09:30 UTC by sheridavandenbent

# Results of merging this

Fixes #

# What has been changed?

# Examples

# Actions to be performed before this can be merged

- [ ] PR depends on #
- [ ] Script to be run

# Security Measures

# Potential Issues / Future considerations

# Assumptions made / Things to add to the wiki
 

# Packages added

# Additional Info

2021-06-18 08:53 UTC, sheridavandenbent commented on config.json
> +  "plots": false,
```suggestion
  "plots": true,
```

2021-06-18 09:11 UTC, geordle commented on modules/setup/datamodule.py
> +from utils.utils import get_ohlcv_indicators, str_to_df, df_to_dict
Remove line 14

2021-06-18 12:11 UTC, geordle requested changes
Nice job!, Mostly just for removing commented tests. I'd not commit these and use git history later

2021-06-18 12:11 UTC, geordle commented on modules/stats/drawdown/for_portfolio.py
> +    max_seen_drawdown["to"] = df.loc[max_seen_drawdown["at"]:].drawdown.eq(0.0).idxmax()
This seems `true-er`
```suggestion
    max_seen_drawdown["to"] = df.loc[max_seen_drawdown["at"]:].drawdown.eq(0.0).iloc[0]
```

2021-06-18 12:11 UTC, geordle commented on test/stats/test_drawdowns.py
> +    # fixture.frame_with_signals['COIN2/BASE'].test_scenario_down_10_up_100_down_75_three_trades()
```suggestion
```

2021-06-18 12:11 UTC, geordle commented on test/stats/test_drawdowns.py
> +    # assert math.isclose(stats.main_results.max_realised_drawdown, -85.52890115608895)
```suggestion
```

2021-06-18 12:11 UTC, geordle commented on test/stats/test_drawdowns.py
> +    # fixture = StatsFixture(['COIN/BASE', 'COIN2/BASE'])
```suggestion
```

2021-06-18 12:11 UTC, geordle commented on test/stats/test_drawdowns.py
> +    # assert math.isclose(stats.coin_res[0].max_realised_drawdown, -90.3940399)
```suggestion
```

2021-06-18 12:11 UTC, geordle commented on test/stats/test_drawdowns.py
> +    # assert math.isclose(stats.coin_res[0].max_realised_drawdown, -60.796)
```suggestion
```

2021-06-18 12:11 UTC, geordle commented on test/stats/test_drawdowns.py
> +#            stats.coin_res[0].max_realised_drawdown
We should use git history for this

```suggestion
```

2021-06-18 12:11 UTC, geordle commented on test/stats/test_coin_insights.py
> +from test.utils.signal_frame import TradeAction
```suggestion
```

2021-06-18 12:15 UTC, geordle requested changes

2021-06-18 12:15 UTC, geordle commented on modules/stats/drawdown/for_portfolio.py
> +    df["drawdown"] = (df["value"] - df["value"].cummax()) / df["value"].cummax()
I'd make this a ratio just to be consistent

2021-06-18 12:16 UTC, DemianVoorhagen6 requested changes
Overall good, I'd say some minor updates needed

2021-06-18 12:16 UTC, DemianVoorhagen6 commented on modules/stats/drawdown/for_portfolio.py
> +    max_seen_drawdown["to"] = df.loc[max_seen_drawdown["at"]:].drawdown.eq(0.0).idxmax()
Have you verified this works for non-exact matches? Say for example the next tick isn't exactly the drawdown but already less, so its not an exact match but a bigger than?

2021-06-18 12:16 UTC, DemianVoorhagen6 commented on modules/stats/drawdown/per_coin.py
> +    trades_open_closed = trade_to_open_close(closed_pair_trades)
Variable names are ambigue and not intuitive.

2021-06-18 12:16 UTC, DemianVoorhagen6 commented on modules/stats/drawdown/per_coin.py
> +    apply_worth_change(df, trades_open_closed)
worth change is also a bit ambigue, is this calculate_closed_trades_roi? We need to use a variable book or something I guess, did you already talk with the rest about that?

2021-06-18 12:16 UTC, DemianVoorhagen6 commented on modules/stats/drawdown/per_coin.py
> +def trade_to_open_close(closed_pair_trades):
Name of function and working of function are a bit vague for me

2021-06-18 12:16 UTC, DemianVoorhagen6 commented on modules/stats/drawdown/per_coin.py
> +def apply_worth_change(df, trades_open_closed):
Same as above

2021-06-18 12:16 UTC, DemianVoorhagen6 commented on modules/stats/drawdown/per_coin.py
> +def apply_fee_at_position_changed(df, fee_percentage, trades_closed_open):
Naming might be a bit better?

2021-06-18 13:45 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +    df["drawdown"] = (df["value"] - df["value"].cummax()) / df["value"].cummax()
it's a ratio though! note the 'divided by cumulative maximum' which makes it a ratio

2021-06-21 14:29 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +    }
I'm not sure if I agree with removing the default values - since we're using the "to" = 0 as a check to see if the drawdown period hasn't ended yet, when printing the result

2021-06-21 14:31 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +    max_seen_drawdown["to"] = df.loc[max_seen_drawdown["at"]:].drawdown.eq(0.0).idxmax()
Fixed in previous commit, resolving conversation

2021-06-21 14:37 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +    max_seen_drawdown["to"] = df.loc[max_seen_drawdown["at"]:].drawdown.eq(0.0).idxmax()
Yes, because at every peak the drawdown will be set to 0.0, so it will always be an exact match!

2021-06-21 14:45 UTC, geordle commented on modules/stats/drawdown/for_portfolio.py
> +    }
aren't these values are always overwritten in lines 15:18?

2021-06-21 14:45 UTC, sheridavandenbent commented on test/stats/test_coin_insights.py
> +from test.utils.signal_frame import TradeAction
Done in recent commit!

2021-06-21 15:05 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +    df["drawdown"] = (df["value"] - df["value"].cummax()) / df["value"].cummax()
Done!

2021-06-21 15:05 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +    df["drawdown"] = (df["value"] - df["value"].cummax()) / df["value"].cummax()
Changed it so it's in line with the rest!

2021-06-21 15:08 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +    }
the 'to' value is not overwritten if the drawdown period hasn't ended yet. But I get your point - I've removed the default values, and just added the 0 value if there is no end date for the drawdown period!

2021-06-21 15:22 UTC, geordle approved these changes

2021-06-22 13:16 UTC, DemianVoorhagen6 requested changes
Good work, just made some small suggestions for readability

2021-06-22 13:16 UTC, DemianVoorhagen6 commented on modules/stats/drawdown/for_portfolio.py
> +    df_next_peak = df_top_slice.loc[df_top_slice["drawdown"] == 0]
```suggestion
    df_next_peak = df_top_slice.loc[df_top_slice["drawdown"] == 1]
```
Shouldn't this be 1? As you reach the previous drawdown value and we use ratios?
I don't fully grasp how the top_slice and next_peak work, maybe we could also check at making better naming? 
df_top_slice > df_after_max_drawdown
df_next_peak > df_after_recovery

2021-06-22 13:16 UTC, DemianVoorhagen6 commented on modules/stats/drawdown/for_portfolio.py
> +        max_seen_drawdown["to"] = 0
Is there a test for this?

2021-06-22 13:16 UTC, DemianVoorhagen6 commented on modules/stats/stats.py
> +    def generate_open_trades_results(self, open_trades: [Trade]) -> list:
```suggestion
    def calculate_results_open_trades(self, open_trades: [Trade]) -> list:
```
Calculate or generate both work I guess, this order in my opinion is a bit nicer

2021-06-22 13:16 UTC, DemianVoorhagen6 commented on modules/stats/stats.py
> +            open_trade_res = OpenTradeResult(pair=trade.pair,
Does 'res' stand for something? Maybe I'm unaware :)

2021-06-22 13:16 UTC, DemianVoorhagen6 commented on modules/stats/stats.py
> +            open_trade_stats.append(open_trade_res)
```suggestion
            stats_open_trades.append(open_trade_res)
```

2021-06-22 13:31 UTC, sheridavandenbent commented on modules/stats/stats.py
> +            open_trade_stats.append(open_trade_res)
Changing to 'left_open_trade_stats' instead

2021-06-22 13:32 UTC, sheridavandenbent commented on modules/stats/stats.py
> +            open_trade_res = OpenTradeResult(pair=trade.pair,
changing to result

2021-06-22 13:34 UTC, sheridavandenbent commented on modules/stats/stats.py
> +    def generate_open_trades_results(self, open_trades: [Trade]) -> list:
changing to 'get_left_open_trades_results'

2021-06-22 14:23 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +        max_seen_drawdown["to"] = 0
Added tests in recent commit. closing conversation

2021-06-22 14:27 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +    df_next_peak = df_top_slice.loc[df_top_slice["drawdown"] == 0]
Bug fixed (thanks for the catch!!), and variables renamed. closing convo!

2021-06-22 14:28 UTC, sheridavandenbent commented on modules/stats/drawdown/per_coin.py
> +    trades_open_closed_timestamps = map_trades_to_open_close_timestamps(closed_pair_trades)
done, resolving convo!

2021-06-22 14:29 UTC, sheridavandenbent commented on modules/stats/stats.py
> +    def generate_open_trades_results(self, open_trades: [Trade]) -> list:
done! closing convo

2021-06-22 14:33 UTC, sheridavandenbent commented on modules/stats/drawdown/per_coin.py
> +    trades_closed_open = [(int(trade.opened_at.timestamp() * 1000), int(trade.closed_at.timestamp() * 1000)) for trade
Changed to trades_closed_opened (because the trades have already happened, so it's past time)

2021-06-22 14:59 UTC, geordle submitted a review, later dismissed

2021-06-22 16:51 UTC, DemianVoorhagen6 approved these changes
Keep up the good work :)

2021-06-22 17:36 UTC, merged