Fix/max realised drawdown simple
dema-trading-ai/engine pull request #286
Opened 2021-06-22 16:09 UTC by sheridavandenbent

# Results of merging this

Simplifies the max realised drawdown, and the nr of losing trades and consecutive losses. Added tests for all three.

# What has been changed?

# Examples

# Actions to be performed before this can be merged

- [ ] PR depends on #280 (simple seen drawdown)

# Security Measures

# Potential Issues / Future considerations

# Assumptions made / Things to add to the wiki
 

# Packages added

# Additional Info

2021-06-23 06:00 UTC, geordle requested changes

2021-06-23 11:30 UTC, DemianVoorhagen6 reviewed
Nice :) No other comments beside this, previous comments & Geordi's.

2021-06-23 11:30 UTC, DemianVoorhagen6 commented on modules/stats/drawdown/per_coin.py
> +def find_trade_timestamps(closed_pair_trades):
```suggestion
def get_trade_timestamps(closed_pair_trades):
```
get sounds more appropriate than find (as they are located already), I couldn't find what 'closed_pair_trades' entails exactly but 'pair' might not be needed? E.g. closed_trades would be sufficient?

2021-06-24 08:25 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +    return max_realised_drawdown
Done, good catch, thanks!

2021-06-24 08:28 UTC, sheridavandenbent commented on modules/stats/drawdown/per_coin.py
> +def find_trade_timestamps(closed_pair_trades):
closed_pair_trades is used here because it's the list of closed trades, but only for one pair. In other parts of the code, closed_trades holds the list of all closed trades of all pairs combined, so I do feel that the name closed_pair_trades adds more information

2021-06-24 08:47 UTC, geordle approved these changes

2021-06-24 09:05 UTC, merged