Feature/config base curr
dema-trading-ai/engine pull request #29
Opened 2021-02-24 16:35 UTC by pvdklei

In this PR I fixed issue #6. I added a 'currency' entry to the config file, and validated it. For instance checking whether this entry exists, and whether it it the same as the currency in the pairs. Finally, I changes the currency symbols shown in the output (only for USD, EUR, GDB and JPY for now, but more can be added easily). 

In addition I moved config validation to a separate module.

2021-02-24 18:11 UTC, dema-trading-ai requested changes

2021-02-24 18:11 UTC, dema-trading-ai commented on config/validations.py
> +                "[ERROR] e.g., if you specified 'USDT' as your currency, you cannot add 'BTC/EUR' as a pair")
Nice!

2021-02-24 18:11 UTC, dema-trading-ai commented on config/checks.py
> +        raise SystemExit
Could you have a look at #30 and implement Marijns' approach of checking in here?

2021-02-25 18:50 UTC, keebrev approved these changes

2021-02-25 18:54 UTC, dema-trading-ai approved these changes

2021-02-25 19:01 UTC, merged