Additional pairs functionality
dema-trading-ai/engine pull request #332
Opened 2021-07-07 08:56 UTC by marijn111

# Results of merging this

Fixes #

# What has been changed?

Functionality to have additional pairs in a strategy has been added. It makes use of the normal data module, and therefore downloads and caches the extra requested candles. Furthermore a function has been added that merges the additional data with the dataframe in such a way that a look-into-the-future bias is prevented. 

# Examples

An example has been added to the advanced strategy example file. 

# Actions to be performed before this can be merged

- [ ] PR depends on #
- [ ] Script to be run

# Security Measures

N/A

# Potential Issues / Future considerations

# Assumptions made / Things to add to the wiki
 

# Packages added

# Additional Info

2021-07-07 09:59 UTC, sheridavandenbent commented on docker-compose.yml
> +        - "./:/usr/src/engine"
Did you mean to push these changes too? I don't think it's a good idea to set the standard image to develop ;)

2021-07-07 10:01 UTC, sheridavandenbent commented on modules/algo/backtesting.py
> +        self.additional_data = additional_data
```suggestion
        self.additional_pairs_data = additional_data
```

Maybe changing the variable names to this (or something like it) makes it easier to understand what kind of data this is

2021-07-07 13:11 UTC, marijn111 commented on docker-compose.yml
> +        - "./:/usr/src/engine"
Woops thats some debug stuff that got left in, thanks for noticing!

2021-07-07 15:03 UTC, sheridavandenbent commented on backtesting/strategy.py
> +        """
```suggestion
```

I would leave out the comment as it's implied in the name of the function

2021-07-07 15:05 UTC, sheridavandenbent commented on resources/setup/strategies/my_strategy_advanced.py
> +        """
```suggestion
    def additional_pairs(self) -> list:
        """
        Specify The additional pairs in tuple format; ("pair", "timeframe")
        """
```

2021-07-07 15:07 UTC, sheridavandenbent commented on resources/setup/strategies/my_strategy_advanced.py
> +        """
If you can put it in the function instead of in comments, that's the way to go!

2021-07-07 15:54 UTC, noudcorten commented on backtesting/strategy.py
> +        timeframe_minutes_additional = parse_timeframe(timeframe_additional)
Don't know if these variable names should contain 'minutes', since parse_timeframe() returns miliseconds.
```suggestion
        timeframe_ms = parse_timeframe(timeframe)
        timeframe_ms_additional = parse_timeframe(timeframe_additional)
```

2021-07-07 15:54 UTC, noudcorten commented on backtesting/strategy.py
> +    def join_additional_data(self, dataframe, additional, timeframe, timeframe_additional, ffill=True):
```suggestion
    def join_additional_data(self, dataframe, additional, timeframe_configured, timeframe_additional, ffill=True):
```
Would make it more clear what 'timeframe' is here.

2021-07-09 07:31 UTC, sheridavandenbent commented on modules/setup/datamodule.py
> +        if not is_same_backtesting_period(history_data) and check_period:
```suggestion
        if check_backtesting_period and not is_same_backtesting_period(history_data):
```
The first one will get checked first, so if it's false the code doesn't have to do the is_same_backtesting_period function! Also I'd rename check_period to check_backtesting_period, just to make it a tad clearer!

2021-07-09 07:37 UTC, sheridavandenbent requested changes
Looks like it's working correctly, nice job!

Do we want to add an example to the MyStrategyAdvanced to show what you could use the additional pairs data for?

2021-07-09 10:07 UTC, marijn111 commented on modules/setup/datamodule.py
> +        if not is_same_backtesting_period(history_data) and check_period:
Good one, thanks!

2021-07-09 10:08 UTC, marijn111 commented
@sheridavandenbent There is an example in the advanced strategy file

2021-07-09 10:17 UTC, sheridavandenbent commented on backtesting/strategy.py
> +        :param ffill: Wether to forward fill the joined dataframe (recommended)
```suggestion
        :param ffill: Whether to forward fill the joined dataframe (recommended)
```

2021-07-09 12:16 UTC, sheridavandenbent approved these changes

2021-07-09 12:37 UTC, merged