Added 3 features + dependency upgrade
dema-trading-ai/engine pull request #334
Opened 2021-07-07 14:15 UTC by rhulshof

- Added support for multiple traces
- Added support for creating an Excel tearsheet file
- Added config option for maximum exposure (to be able to spend i.e. 100% of balance into 1 single coin)
- Upgrade TA-Lib dependency to version 0.4.20 (from 0.4.19)

2021-07-07 15:56 UTC, geordle reviewed
Awesome! Code is good & even follows our "undocumented" guidelines, kudos. There are some things regarding max_exposure that will take some deliberation but rest looks good.

2021-07-07 15:56 UTC, geordle commented on modules/stats/tradingmodule.py
> +        spend_amount = (self.max_exposure / 100.) * self.realised_profit
Unfortunately we'll need to think about this a bit more before we can add this feature. In its current state it would significantly impact existing strategies. My thought is that the previous implementation was the way it is so that strategies on pairs would always have enough balance to get into position (this makes results more reproducible. Just think about the order in which trades are executed having effect on results in this case). Could you maybe explain the behaviour you're trying to achieve here? Maybe we can come up with a different solution together that fits your needs (exposure per pair?, dynamic stake amount?) cc: @DemianVoorhagen6 @sheridavandenbent

2021-07-07 15:56 UTC, geordle commented on modules/output/plots.py
> +        rows += 1
`rows = 1 + len(subplot_indicator)`

2021-07-07 15:56 UTC, geordle commented on modules/output/__init__.py
> +    df.to_excel('data/backtesting-data/tearsheet.xlsx')
I needed to install a dependency for this called `openpyxl`. Maybe this needs to be added to `requirements.txt`

2021-07-13 14:36 UTC, rhulshof commented on modules/stats/tradingmodule.py
> +        spend_amount = (self.max_exposure / 100.) * self.realised_profit
The goal is to analyze what the correlation is between several coins. I.e. one can decide to spend 100% of the balance on whichever coin displayes a buy signal first. Or one can decide to spend 50% per coin, whilst watching at 3 coins separately. So whichever 2 coins give their buy signal first, will end up with 50% of the balance. The backtester already supports this by displaying a "cannot buy" message in the terminal message, whenever the balance is already used on other coins.

Despite the above, I totally agree with your objections. It indeed would break existing setups. What I can do, is make sure the behavior remains as it was whenever the configuration setting is missing and/or None. Only when it actually has a percentage value, it will follow the above logic. This way, backtesters are completely in control. Do you agree? If yes, I will update the pull request.

2021-07-14 06:24 UTC, geordle commented on modules/stats/tradingmodule.py
> +        spend_amount = (self.max_exposure / 100.) * self.realised_profit
That `cannot buy` message should not be possible in recent versions (from 2 months ago onwards) of the engine.

I'm OK with that but, what if we changed the `max_exposure` implementation a little bit. Currently, when wanting to distribute balance across trading pairs you'd have to manually  `100 / amount_of_pairs` and fill that for the `max_exposure` variable. Everytime you change your pairs you'd have to update this variable. If we change this to `exposure_per_trade` (note the ~~max~~, since it will actually decide exposure, not cap it) we could spread funds evenly across pairs with a value of `1.`, flatten sways by lowering it `FI: .5` or achieve what you're trying to do by setting it by raising `2`.

the adjusted formula would be something in the lines of
```python
exposure_per_pair = config["exposure_per_trade"] or 1.
splits_amount = min(self.max_open_trades, self.amount_of_pairs) # recent change
spend_amount = ((1. / splits_amount) * exposure_per_pair) * self.realised_profit
```

What do you think?

2021-07-14 06:28 UTC, geordle commented on modules/stats/tradingmodule.py
> +        spend_amount = (self.max_exposure / 100.) * self.realised_profit
I'm not yet decided on whether we should use ratio or percentages, or on the naming

2021-07-16 15:42 UTC, rhulshof commented on modules/output/__init__.py
> +    df.to_excel('data/backtesting-data/tearsheet.xlsx')
Indeed. Will do.

2021-07-16 15:44 UTC, rhulshof commented on modules/stats/tradingmodule.py
> +        spend_amount = (self.max_exposure / 100.) * self.realised_profit
Stoploss setting already uses percentages, not ratio's. Therefore used the same here. Should be the way to go right?

2021-07-16 15:45 UTC, rhulshof commented on modules/stats/tradingmodule.py
> +        spend_amount = (self.max_exposure / 100.) * self.realised_profit
I like your change and will build it accordingly.

2021-07-16 15:46 UTC, rhulshof commented on modules/output/plots.py
> +        rows += 1
Clever :)

2021-07-23 12:41 UTC, rhulshof commented
Request was updated. It now includes all discussed topics.

2021-07-23 12:42 UTC, geordle commented on modules/public/trading_stats.py
> +    exposure_per_trade: int
```suggestion
    exposure_per_trade: float
```

2021-07-23 12:42 UTC, geordle commented on modules/stats/stats_config.py
> +    exposure_per_trade: int
```suggestion
    exposure_per_trade: float
```

2021-07-23 12:43 UTC, geordle commented on modules/stats/tradingmodule_config.py
> +    exposure_per_trade: int
```suggestion
    exposure_per_trade: float
```

2021-07-23 12:46 UTC, geordle approved these changes

2021-07-23 12:55 UTC, geordle requested changes
There are a few things left regarding that exposure ratio format. think percentages would be nice for user input, and internally normalized (1.) ratios are nice because they"re normal :). i think tests should also succeed after these changes

2021-07-23 12:55 UTC, geordle commented on config.json
> +  "exposure-per-trade": 1,
```suggestion
  "exposure-per-trade": 100,
```

2021-07-23 12:55 UTC, geordle commented on config.example.json
> +  "exposure-per-trade": "100",
```suggestion
  "exposure-per-trade": 100,
```

2021-07-23 12:55 UTC, geordle commented on modules/setup/config/__init__.py
> +        config_module.exposure_per_trade = config["exposure-per-trade"]
```suggestion
        config_module.exposure_per_trade = config["exposure-per-trade"] / 100.
```

2021-07-23 12:55 UTC, geordle commented on test/stats/stats_test_utils.py
> +exposure_per_trade = 100
```suggestion
exposure_per_trade = 1.
```

2021-07-23 12:55 UTC, geordle commented on modules/output/results.py
> +    settings_table.add_row("Max. exposure per trade", str(self.exposure_per_trade))
```suggestion
    settings_table.add_row("Exposure per trade", str(self.exposure_per_trade * 100) + " %")
```

2021-07-23 13:00 UTC, geordle commented on test/stats/stats_test_utils.py
> +            exposure_per_trade=exposure_per_trade,
```suggestion
            exposure_per_trade=exposure_per_trade,
             tearsheet=False,
```

2021-07-27 12:51 UTC, rhulshof commented
On my Windows machine all pytest's are failing. Even when running it on the "main" branch. All other issues I have fixed. Do you know why it's still failing?

2021-07-27 12:55 UTC, geordle commented
> On my Windows machine all pytest's are failing. Even when running it on the "main" branch. All other issues I have fixed. Do you know why it's still failing?

Hmm, weird. In pipelines and local they seem to work for me. If end-to-end tests succeed I'm completely fine with the changes. Thanks a lot!

2021-07-27 12:55 UTC, geordle commented
> On my Windows machine all pytest's are failing. Even when running it on the "main" branch. All other issues I have fixed. Do you know why it's still failing?

I'll take a look on windows as soon as I can

2021-07-27 13:32 UTC, geordle requested changes

2021-07-27 13:32 UTC, geordle commented on modules/setup/config/__init__.py
> +        config_module.tearsheet = config["tearsheet"]
Ah yeah, this is a breaking change. existing configs will struggle on this (hence the failing end-2-end tests).
The following will access safely and provide a default value.
```suggestion
        config_module.exposure_per_trade = config.get("exposure-per-trade", 100.) / 100.
        config_module.plots = config["plots"]
        config_module.tearsheet = config.get("tearsheet", False)
```

2021-07-27 13:32 UTC, geordle commented on modules/setup/config/__init__.py
> +        config_module.tearsheet = config["tearsheet"]
I'm checking pytest on windows now but should stop us from merging

2021-07-27 14:14 UTC, geordle commented
Tests on windows are failing because timestamp is broken for one day past epoch on windows. https://stackoverflow.com/a/67904074

Might fix this later

2021-07-29 11:41 UTC, geordle approved these changes

2021-07-29 11:44 UTC, merged