Automaticaly open plots after creating (plotly did not open it by default anymore)
dema-trading-ai/engine pull request #372
Opened 2021-08-23 07:28 UTC by rhulshof

Plotly did not open the chart by default anymore. This commit is only to stick with the previous behavior.

2021-09-02 09:55 UTC, sheridavandenbent submitted a review, later dismissed
Good catch, thank you!

2021-10-06 13:12 UTC, rhulshof commented
Another commit was added. Since this pull request appeared to be still open; the commit was appended. Nevertheless, both are worth pulling :)

2021-10-11 06:08 UTC, geordle requested changes

2021-10-11 09:59 UTC, rhulshof commented
1. It still states changes are requested, whilst I already committed the requested changes. Am I missing something or is this PR ready to be merged now?
2. Interesting why the pytest-test keeps failing? Something I am doing wrong here?

2021-10-12 04:29 UTC, geordle commented on modules/output/plots_per_coin.py
> +    fig.write_html("data/backtesting-data/plots/plot%s.html" % pair.replace("/", ""), config={'scrollZoom': True}, auto_open=True)
Would you mind still removing this bit right here?

```suggestion
    fig.write_html("data/backtesting-data/plots/plot%s.html" % pair.replace("/", ""), config={'scrollZoom': True})
```

2021-10-12 14:41 UTC, geordle approved these changes

2021-10-12 14:47 UTC, merged