Add log scaling to equity plot and coin plots
dema-trading-ai/engine pull request #400
Opened 2021-10-29 11:55 UTC by sheridavandenbent

Adds log scaling to the equity plot and the coin price plots. Log scaling is default on for the equity plot, and default off for the coin price plots.

Also removes a (now) redundant check to remove old plots in an old folder.

2021-11-01 11:21 UTC, marijn111 commented on config.json
> +  },
Can't we switch to the log scale within the plot? That would be the ideal implementation.
https://community.plotly.com/t/set-linear-or-log-axes-from-button-or-drop-down-menu-python/34927

2021-11-02 10:56 UTC, sheridavandenbent commented on config.json
> +  },
Done! Thanks for the great suggestion!

2021-11-02 12:18 UTC, marijn111 commented
This doesn't seem like it is working correctly just yet. Very zoomed out and the colouring is inverted when going negative. 

![newplot](https://user-images.githubusercontent.com/39378193/139844316-258128fd-00fa-4621-b23e-4c47811962fc.png)

2021-11-03 10:53 UTC, marijn111 requested changes

2021-11-03 10:53 UTC, marijn111 commented on modules/output/equity_plot.py
> -    fig.update_yaxes(range=[min_value, max_value])
Could you re-add this line?

2021-11-04 10:32 UTC, sheridavandenbent commented on modules/output/equity_plot.py
> -    fig.update_yaxes(range=[min_value, max_value])
Added this functionality in a slightly different way!

2021-11-04 12:36 UTC, marijn111 approved these changes

2021-11-04 12:48 UTC, merged