Fix/small changes
dema-trading-ai/engine pull request #411
Opened 2021-11-05 09:03 UTC by WillemGerritzen

# Results of merging this

Fixes #398 

# What has been changed?

Added or changed small printouts here and there

2021-11-05 10:38 UTC, sheridavandenbent commented on config.json
> +  "backtesting-to": "2021-11-01",
```suggestion
  "backtesting-from": "2021-01-01",
  "backtesting-to": "2021-07-01",
```

Maybe have it from the first of January? That looks a bit neater!

2021-11-05 10:39 UTC, sheridavandenbent commented on modules/setup/config/__init__.py
> +
What is this constant used for?

2021-11-05 10:40 UTC, sheridavandenbent commented on modules/setup/config/__init__.py
> +        ConfigModule.strategy_name = config['strategy-name']
```suggestion
        config_module.strategy_name = config['strategy-name']
```

Shouldn't it modify the instance of the class, not the main class itself?

2021-11-05 10:40 UTC, sheridavandenbent requested changes
See comments!

2021-11-08 13:27 UTC, WillemGerritzen commented on config.json
> +  "backtesting-to": "2021-11-01",
Indeed!

2021-11-08 14:06 UTC, WillemGerritzen commented on modules/setup/config/__init__.py
> +        ConfigModule.strategy_name = config['strategy-name']
Changes have been made.

2021-11-08 15:15 UTC, sheridavandenbent approved these changes

2021-11-08 15:17 UTC, merged