Feat/ratios
dema-trading-ai/engine pull request #435
Opened 2021-12-06 15:02 UTC by WillemGerritzen

# Continuation of #428 

# What has been changed?

Added two new metrics, the Sharpe  and sortino ratios, to be printed out on the performance table

# Potential Issues / Future considerations

* Currently, the risk free return is set at 0 and can't be changed
* The ratios includes all coins 
Both of these points should be improved upon in the future to make this metric more interesting

2021-12-20 14:52 UTC, sheridavandenbent commented on modules/setup/config/validations.py
> +            print_warning('The time period selected is not long enough to display a 3-years ratios')
I think we can write the warnings a bit better. Which ratio? And why is it still displayed, if the warning says 'it's not long enough to display'? Furthermore, 'a 3-years ratios' looks weird, I'd change that too.

I'd suggest changing it to something like

'The time period is less than 90 days. The 90 day and 3 year Sharpe and Sortino ratio's are only calculated on the available data."
'The time period is less than 3 years. The 3 year Sharpe and Sortino ratio's are only calculated on the available data."

2021-12-20 14:55 UTC, sheridavandenbent commented on modules/setup/config/validations.py
> +        print_warning('Unable to compute ratios: No trades were made')
When running the backtest without making any trades (not generating buy signals) this warning is not given, and it throws a runtimewarning:

RuntimeWarning: invalid value encountered in double_scalars
  sortino_ratio = additional_return / target_downside_deviation
  
  The runtime warning needs to be fixed. Furthermore, more statistics rely on trades being made, and are simply 0 or - when no trades are made. This makes it very clear that no trades were made. I don't think this warning is specifically required.

2021-12-20 14:56 UTC, sheridavandenbent commented on modules/setup/config/validations.py
> +        print_warning('Unable to compute ratios: The backtesting period needs to be at least 24h')
Just like I mentioned below, I think this can be written a bit better!

2021-12-20 14:57 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +def convert_dataframe(capital_per_timestamp: dict, risk_free: float) -> pd.DataFrame:
This function can be named better - I'd change it to convert_dict_to_dataframe. or if you want to make it more precise, change_capital_dict_to_dataframe.

2021-12-20 14:57 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +def convert_dataframe(capital_per_timestamp: dict, risk_free: float) -> pd.DataFrame:
It would also be better to explain in the comment a little bit more about where this is used!

2021-12-20 14:59 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +    df = df.sort_index()
Why do you specifically first remove the first value and then add it again later?

2021-12-20 15:00 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +
General comment - why is this in the drawdown calculation folder?

2021-12-20 15:21 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +    else:
Are these if statements really necessary? It looks like truncate automatically doesn't truncate if you give a value that is out of scope of the dataframe. Did you test this?

2021-12-20 15:23 UTC, sheridavandenbent commented on modules/stats/stats.py
> +                           ratios=(sharpe_90d, sharpe_3y, sortino_90d, sortino_3y)
ratios? Which ratios? ;)

2021-12-20 15:26 UTC, sheridavandenbent commented on test/stats/test_coin_insights.py
> +
We don't want to have to create these for every single test file - let's put it all into the test utils instead!

2021-12-20 15:27 UTC, sheridavandenbent commented on test/stats/test_drawdowns.py
> +    assert stats.main_results.drawdown_at == 1577833200000
Look, I get that it needs to be more like real data and it's good for future proofing. But let's make it easy to spot mistakes, and change it to datetime instead of timestamp. What do you think?

2021-12-20 15:28 UTC, sheridavandenbent commented on test/stats/test_main_results.py
> +    assert math.isclose(stats.main_results.ratios[0], 0.1015, abs_tol=0.0001)
It would be prettier and easier to see (you wouldn't need any comments) if this could be written as stats.main_resuilts.sharpe_ratio_90d

2021-12-20 15:29 UTC, sheridavandenbent commented on test/stats/test_main_results.py
> +    # Three trades, one per day; should return an actual value
Three trades and one per day, but 3 years? This seems improbable!

2021-12-20 15:30 UTC, sheridavandenbent commented on test/utils/signal_frame.py
> +        self.current_time = 1577833200000
Let's add the datetime that it's set at in a comment here, so it's immediately clear

2021-12-20 15:31 UTC, sheridavandenbent commented on test/utils/signal_frame.py
> +    def add_entry(self, open=1., high=1., low=1., close=1., volume=1., buy=0, sell=0, stoploss=0, timestep=DAILY):
I don't agree with setting the timestep as standard value to daily - if we want to get representative for how our users are using the engine, it'd be better to set it somewhere in the 30m - 4h range.

2021-12-20 15:32 UTC, sheridavandenbent commented on test/utils/signal_frame.py
> +    def add_entry(self, open=1., high=1., low=1., close=1., volume=1., buy=0, sell=0, stoploss=0, timestep=DAILY):
I figured out why you get an error now and not in other test cases - because you're actually adjusting the base function. Codacy is right, we shouldn't overwrite open - but let's push it through now, and refactor the tests sometime this week.

2021-12-20 15:33 UTC, sheridavandenbent commented on test/utils/signal_frame.py
> +    def test_scenario_flat_one_trade(self, timestep=ONE_MIL):
Why is this one standard set to one mil why the rest is on daily?

2021-12-20 15:34 UTC, sheridavandenbent commented on test/utils/signal_frame.py
> +        valid_days = [90, 1095]
Why the minimum of 90 days?

2021-12-20 15:34 UTC, sheridavandenbent commented on test/utils/signal_frame.py
> +        valid_days = [90, 1095]
Why do you limit it to these amount of days only?

2021-12-20 15:34 UTC, sheridavandenbent requested changes
See comments on the code!

2021-12-23 09:22 UTC, WillemGerritzen commented on modules/setup/config/validations.py
> +        print_warning('Unable to compute ratios: No trades were made')
I can't reproduce this problem, but I think it's because it lets it be divided by zero so will add a fix for that.

2021-12-23 10:10 UTC, WillemGerritzen commented on modules/stats/drawdown/for_portfolio.py
> +    df = df.sort_index()
Because the index starts with 0.0 and needs to be removed for the to_datetime() func above to work. Adding a comment explaining this

2021-12-23 15:38 UTC, WillemGerritzen commented on test/utils/signal_frame.py
> +    def add_entry(self, open=1., high=1., low=1., close=1., volume=1., buy=0, sell=0, stoploss=0, timestep=DAILY):
Most tests either need daily or don't care, thus quicker to set daily here than some other value that ends up being changed a bunch of times

2021-12-23 15:39 UTC, WillemGerritzen commented on test/utils/signal_frame.py
> +    def test_scenario_flat_one_trade(self, timestep=ONE_MIL):
As above, all the tests that use this function need it to be at one millisecond, so faster to set it to that here once

2021-12-23 15:42 UTC, WillemGerritzen commented on test/stats/test_main_results.py
> +    # Three trades, one per day; should return an actual value
Not sure what you mean. The point is to simulate movement every day for three years and make sure it's still able to compute the ratios

2021-12-23 15:51 UTC, WillemGerritzen commented on test/utils/signal_frame.py
> +        valid_days = [90, 1095]
90 days and 3 years. Are we looking other timeperiods>

2021-12-24 12:48 UTC, sheridavandenbent commented on test/utils/signal_frame.py
> +        self.current_time = 1577833200000
Can you still add this in a comment?

2021-12-24 12:49 UTC, sheridavandenbent commented on test/utils/signal_frame.py
> +        self.current_time = 1577833200000
```suggestion
        self.current_time = 1577833200000 # 2020-01-01
```

2021-12-24 14:37 UTC, sheridavandenbent approved these changes

2021-12-24 14:39 UTC, merged