Add average market change line to equity plot
dema-trading-ai/engine pull request #454
Opened 2021-12-27 12:58 UTC by WillemGerritzen

# What has been changed?

Added a trace to the equity plot tracking the average market change for all coins 

# Potential Issues / Future considerations

The computation of the average starting capital assumes an equal division between all coins. This will need to be refactored once we allow users to specify how to allocate the funds.

# Assumptions made / Things to add to the wiki
 
Might be good to add (if not already the case) in the docs that plotly allows the traces to be toggled by clicking on their respective legends

2021-12-28 09:10 UTC, sheridavandenbent commented on modules/output/equity_plot.py
> +    df_coins = compute_average_market_change(stats.df, stats.capital_per_timestamp[0])
Be mindful of your variables - while it's clear to you that df_coins means the average market change over all the coins normalized by the starting capital, that might not be clear to other people reading your code.

How about 'avg_market_change_coins'? (Be sure to change it elsewhere in the code too

```suggestion
    avg_market_change_coins = compute_average_market_change(stats.df, stats.capital_per_timestamp[0])
```

2021-12-28 09:12 UTC, sheridavandenbent commented on modules/output/equity_plot.py
> +            "name": "Average market change",
```suggestion
            "name": "Average Market Change",
```

It looks better when it's all capitalised, imho :)
However, this is very much nitpicking on my side, so if you don't agree feel free to disregard this.

2021-12-28 09:15 UTC, sheridavandenbent commented on modules/output/plots.py
> +    for coin, ohlcv in df_stats.items():
This all looks really neat. Well done on restructuring this!

2021-12-28 09:17 UTC, sheridavandenbent requested changes
Overall really good - I have one small feedback point on the naming of variables, but that's it. Great job on this one 👍

2021-12-30 09:24 UTC, WillemGerritzen commented on modules/output/plots.py
> +    for coin, ohlcv in df_stats.items():
Thanks!

2022-01-03 08:03 UTC, sheridavandenbent approved these changes
Looks great!

2022-01-03 12:36 UTC, merged