[Feat] Hyperopt intermediate results
dema-trading-ai/engine pull request #502
Opened 2022-01-25 10:29 UTC by sheridavandenbent

# Results of merging this
When you run hyperopt with a large number of trials, you might want to exit halfway because it's taking a long while - but you still want the best results up to that moment. This PR makes that a reality.

When running the Engine with hyperopt on, you will be informed of how to exit halfway through ("If you want to exit the program halfway, press 'ctrl + c', and you will get the intermediate results."). If you then press ctrl + c sometime during the running of hyperopt, the best results up till that moment will be printed. If you press ctrl+c before any trials are run, it will inform you that no trials have been completed yet, and that therefore there are no best results available.

2022-01-25 11:20 UTC, marijn111 submitted a review, later dismissed

2022-01-25 11:20 UTC, marijn111 commented
Apart from the small codacy thing, looks good!

2022-01-28 13:19 UTC, WillemGerritzen requested changes
Made a comment

2022-01-28 13:19 UTC, WillemGerritzen commented on main_controller.py
> +                print_info(f"Best results: {study.best_params}")
Wouldn't it make more sense to just test the length of study.best_params? using checks for errors has always felt a bit hackish to me.

2022-01-28 13:24 UTC, sheridavandenbent commented on main_controller.py
> +                print_info(f"Best results: {study.best_params}")
Good point. That's way better. I'll get on it

2022-02-11 11:38 UTC, sheridavandenbent commented on main_controller.py
> +                print_info(f"Best results: {study.best_params}")
Okay yeah, the problem is that best_params is not a variable but a function. Which means that I can't test the lenght or anything, as it throws a valueerror in my face straight away, the moment I try to access it. Optuna isn't smart enough that it actually has a variable denoting any kind of nr of trials run, so it'll take a lot of work to rewrite this into something not-hackish (which might turn out even more hack-ish anyway). I'm in favour of keeping this as-is. What do you think?

2022-02-11 13:52 UTC, WillemGerritzen approved these changes
lgtm

2022-02-11 14:51 UTC, merged