[ENG-58] Outperforming & Profitable Months
dema-trading-ai/engine pull request #516
Opened 2022-02-11 15:05 UTC by sheridavandenbent

# Results of merging this
Adds the metric Outperforming vs Market Months, and Profitable Months. Also bugfixes the outperforming & profitable weeks. Adds a new table in order to give these metrics some space, and fancy colours.

2022-02-11 15:05 UTC, sheridavandenbent commented on config.json
> +  "backtesting-to": "2021-07-02",
```suggestion
  "backtesting-from": "2021-01-01",
  "backtesting-to": "2021-07-01",
```

2022-02-11 15:06 UTC, sheridavandenbent commented on config.json
> +  "pairs": ["BTC"],
```suggestion
  "pairs": ["BTC", "LTC", "ETH"],
```

2022-02-14 11:41 UTC, WillemGerritzen requested changes

2022-02-14 11:41 UTC, WillemGerritzen commented on modules/output/results.py
> +        coin_perf_per_timeframe_table = Table(title="Coin Performance per Timeframe",
Would it make more sense to have the coin at the end of the title? Something like 'Weekly and Monthly Performance per Coin'

2022-02-14 11:41 UTC, WillemGerritzen commented on resources/setup/strategies/my_strategy.py
>              (
Did you remove the RSI > 70 on purpose?

2022-02-14 12:37 UTC, sheridavandenbent commented on modules/output/results.py
> +        coin_perf_per_timeframe_table = Table(title="Coin Performance per Timeframe",
Yes! Good idea. Renaming it.

2022-02-14 12:37 UTC, sheridavandenbent commented on resources/setup/strategies/my_strategy.py
>              (
Nope. I'll remove it. Thanks!

2022-02-14 13:30 UTC, sheridavandenbent commented on resources/setup/strategies/my_strategy.py
>                  (dataframe['volume'] > 0)
```suggestion
                (dataframe['rsi'] > 70) &
                (dataframe['volume'] > 0)
```

2022-02-14 13:45 UTC, merged