[ENG 83] Restructure dataframe starting capital
dema-trading-ai/engine pull request #527
Opened 2022-02-21 09:28 UTC by sheridavandenbent

# Results of merging this
All the dataframes concerning the capital now start with one timestep before actual starting time. So if the timeframe is 30 minutes, and the starting date is 01-01-2020 00:00, the starting capital is saved in the dataframe at date 31-12-2020, 23:30.

2022-02-21 11:17 UTC, WillemGerritzen requested changes
Left some comments, maybe worth talking offline for some of them?

2022-02-21 11:17 UTC, WillemGerritzen commented on modules/stats/metrics/profit_ratio.py
> +def with_copied_initial_row(df: DataFrame) -> pd.DataFrame:
Nitpicking here but maybe worth doing pd.Dataframe so we don't need to import both pandas and pd.DataFrame?

2022-02-21 11:17 UTC, WillemGerritzen commented on modules/stats/tradingmodule.py
> +        timestep_before_start = self.config.backtesting_from - self.config.timeframe_ms
I'm not sure I understand why we would need to start one timestep behind?

2022-02-21 11:17 UTC, WillemGerritzen commented on modules/stats/utils.py
>      return df
This is so much cleaner now, it heals my soul

2022-02-21 11:17 UTC, WillemGerritzen commented on modules/stats/utils.py
>              df = df.resample('D').apply(lambda x: x.iloc[-1])
Don't know why this is a thing but maybe we can rename x to row or something? Makes a little clearer

2022-02-21 11:17 UTC, WillemGerritzen commented on resources/setup/strategies/my_strategy.py
>              (
Relatively sure those aren't meant to be deleted ;)

2022-02-21 11:17 UTC, WillemGerritzen commented on test/stats/stats_test_utils.py
> +            "backtesting-to": "2020-07-01",
Are the years here changed on purpose?

2022-02-21 11:17 UTC, WillemGerritzen commented on test/stats/stats_test_utils.py
> +import pytz
Proper nitpick here but I would move this above the pandas import to keep it clean

2022-02-21 11:17 UTC, WillemGerritzen commented on test/stats/stats_test_utils.py
> +def date(timestamp) -> datetime:
Maybe we can, generally speaking, have every argument be type hinted? For code clearness and all that

2022-02-21 11:17 UTC, WillemGerritzen commented on test/stats/stats_test_utils.py
> +def create_test_date(year=1970, month=1, day=1, hour=0, minute=0, second=0) -> datetime:
Not sure I understand the purpose of the functions

2022-02-21 11:17 UTC, WillemGerritzen commented on test/utils/signal_frame.py
> +        self.current_time = ccxt.binance.parse8601("2020-01-01T00:00:00Z")
Why don't we use datetime.timestamp(year=2020, month=1, day=1) instead? Would not require  ccxt and would be more inline with how we handle dates throughout the test IMO

2022-02-22 09:41 UTC, sheridavandenbent commented on modules/stats/drawdown/for_portfolio.py
> +def get_longest_drawdown(per_timestamp_dict: dict) -> Dict[str, timedelta or bool]:
Fair, but tbf I only changed this so I could run the code on my side - this is part of the longest drawdown code, so I'd say do change it when you make a PR for the longest drawdown addition. But before you do that, I'd like to talk with you and see if we can figure out a way to not have 'or' or 'union' functionality in the return types. I'd personally rather have timedelta or 'none' for example, but I'm not sure if that would work for you

2022-02-22 09:41 UTC, sheridavandenbent commented on modules/stats/metrics/profit_ratio.py
> +def with_copied_initial_row(df: DataFrame) -> pd.DataFrame:
That's a good kind of nitpicking! Good idea! I'll change it

2022-02-22 09:43 UTC, sheridavandenbent commented on modules/stats/metrics/profit_ratio.py
> +def with_copied_initial_row(df: DataFrame) -> pd.DataFrame:
Done!

2022-02-22 09:43 UTC, sheridavandenbent commented on modules/stats/tradingmodule.py
> +        timestep_before_start = self.config.backtesting_from - self.config.timeframe_ms
Because we need to save the starting capital somewhere - we can't save it on the starting timestep because it will be overwritten the moment there's a buy signal on the first tick, since it'll buy, and remove the fee from the capital.

2022-02-22 09:44 UTC, sheridavandenbent commented on modules/stats/utils.py
>              df = df.resample('D').apply(lambda x: x.iloc[-1])
Yes, good idea. :v:

2022-02-22 09:46 UTC, sheridavandenbent commented on resources/setup/strategies/my_strategy.py
>              (
Errrrr.. Good catch! 😅

2022-02-22 09:48 UTC, sheridavandenbent commented on resources/setup/strategies/my_strategy_advanced.py
> +            ("BTC/USDT", "1d")
```suggestion
            ("BTC/USDT", "4h")
```

2022-02-22 09:48 UTC, sheridavandenbent commented on resources/setup/strategies/my_strategy_advanced.py
> +        dataframe = self.join_additional_data(dataframe, add_btc_data, self.timeframe, "1d")
```suggestion
        dataframe = self.join_additional_data(dataframe, add_btc_data, self.timeframe, "4h")
```

2022-02-22 09:48 UTC, sheridavandenbent commented on resources/setup/strategies/my_strategy_advanced.py
> +                (dataframe['rsi_BTC/USDT_1d'] < 30)     # additional pair usage
```suggestion
                (dataframe['rsi_BTC/USDT_4h'] < 30)     # additional pair usage
```

2022-02-22 09:50 UTC, sheridavandenbent commented on test/stats/stats_test_utils.py
> +            "backtesting-to": "2020-07-01",
Yes, because the tests are written in such a way that 2020 was the base point. I can change the tests to have the test config reflect the default config value, but this was faster

2022-02-22 09:52 UTC, sheridavandenbent commented on test/stats/stats_test_utils.py
> +import pytz
Done, and cleaned up the pandas import too

2022-02-22 09:54 UTC, sheridavandenbent commented on test/stats/stats_test_utils.py
> +def date(timestamp) -> datetime:
Yes good point, thanks

2022-02-22 09:56 UTC, sheridavandenbent commented on test/stats/stats_test_utils.py
> +def create_test_date(year=1970, month=1, day=1, hour=0, minute=0, second=0) -> datetime:
They're there to make it easy to see in tests which dates are compared - instead of creating the timestamp, you'd call the create_test_timestamp with the correct year, month, day, etc. That way it's clear to see immediately which date and time it should be, if the test fails.

2022-02-22 09:56 UTC, sheridavandenbent commented on test/stats/stats_test_utils.py
> +def create_test_date(year=1970, month=1, day=1, hour=0, minute=0, second=0) -> datetime:
I just think it looks cleaner in the tests now :)

2022-02-22 10:08 UTC, sheridavandenbent commented on test/utils/signal_frame.py
> +        self.current_time = ccxt.binance.parse8601("2020-01-01T00:00:00Z")
I've changed it to use the new test date creator I made!

2022-02-22 10:09 UTC, sheridavandenbent commented on utils/utils.py
> +        timeframe_time = int(items[1]) * DAY
```suggestion
```

2022-02-22 10:17 UTC, sheridavandenbent commented
@WillemGerritzen I've gone through your comments and implemented them and/or commented on them! This PR is ready for re-reviewing!

2022-02-24 10:42 UTC, WillemGerritzen approved these changes
lgtm

2022-02-24 11:18 UTC, merged