Review/backtest results overview
dema-trading-ai/engine pull request #53
Opened 2021-03-02 12:54 UTC by pvdklei

As #17 suggested that `BackTesting.generate_backtesting_results()` was too large, and could use some cleanup, I refactored this function. I did this by creating some new result-models: `MainResults`, `CoinInsights` and `OpenTradeResult` in `results.py`, that handle their own visualisation. By removing the `print` statements to other classes, `BackTesting` can fully focus on only calculating these results. 

A next step would be to use these models in all places and earlier on in calculations, as the values that these models own are currently stored temporarily in `dict`'s and other variables (unnecessary memory transfers) in the methods that create these results in `BackTesting`.

Note: this PR does not fully solve #17.

2021-03-02 20:23 UTC, dema-trading-ai approved these changes

2021-03-02 20:24 UTC, dema-trading-ai reviewed
What is missing from #17 ?

2021-03-03 11:17 UTC, pvdklei commented
Actually just the first bullet point in #17 is solved: "General 'generate backtest result' method. This method is way to large"

2021-03-03 15:49 UTC, pvdklei commented
#17 is now fully solved, apart from putting "from - to" on one line (that looked odd, and made the table too wide) and adding total fee paid (fee calculations must first be implemented).

2021-03-03 19:56 UTC, keebrev commented
> #17 is now fully solved, apart from putting "from - to" on one line (that looked odd, and made the table too wide) and adding total fee paid (fee calculations must first be implemented).

Very nice! Alright, if from - to looks odd, let's skip it. It was just an idea to improve the results visually.

2021-03-03 20:04 UTC, keebrev requested changes

2021-03-03 20:04 UTC, keebrev commented on makefile
> +	docker run --rm -v "$(shell pwd):/engine" dema-engine:alpha
Really like this! But could you please add to README how we can use this and what is needed for this to work? (I assume we need some binary package)

2021-03-03 20:10 UTC, keebrev commented on backtesting/results.py
> +        print("| Stoploss: \t\t\t%s" % self.configured_stoploss + "\t" + currency_symbol)
Stoploss is not in the base currency but in percentages. Could you please fix? :)

2021-03-04 10:20 UTC, pvdklei commented on makefile
> +	docker run --rm -v "$(shell pwd):/engine" dema-engine:alpha
Accidentally left it in, but nice that you like it!! You need `make` installed, but I think it's installed by default on most computers. I'll add it.

2021-03-04 10:20 UTC, pvdklei commented on backtesting/results.py
> +        print("| Stoploss: \t\t\t%s" % self.configured_stoploss + "\t" + currency_symbol)
Sure!

2021-03-04 10:42 UTC, pvdklei commented
Changed the $ to a % and changed the README. Can someone on windows and linux maybe check if `make` is installed by default? Thought so, but can't get confirmation online or some good one-liners to install it.

2021-03-04 15:46 UTC, keebrev commented
> Changed the $ to a % and changed the README. Can someone on windows and linux maybe check if `make` is installed by default? Thought so, but can't get confirmation online or some good one-liners to install it.

I am not sure for both the OS's. As every environment will differ, I don't think you can assume that it's installed. However, it's only 1 simple step installing / checking whether it's installed.

Checking whether it's installed
```
make --version
```

Installing on Linux
```
 sudo apt install make
```

Installing on Windows (chocolately required)
```
choco install make
```

2021-03-04 16:45 UTC, pvdklei commented
True, so I've added it. To not bloat the README too much, I've put the `make` install instructions in-line with the rest.

2021-03-05 10:10 UTC, keebrev approved these changes

2021-03-05 10:10 UTC, merged