Feature/Docker pipeline
dema-trading-ai/engine pull request #76
Opened 2021-03-10 18:24 UTC by WillemGerritzen

# Fixes

Fixes #40 

# What has been changed?

Add a .yml file to deploy to Docker and Github Packages when pushing to release/stable.

# Examples

![image](https://user-images.githubusercontent.com/40299395/110677267-445e9b00-81d5-11eb-8c2b-69725f9cb478.png)

Example from another repo. When a push is made to release/stable, the steps seen above are triggered in `Actions`.

# Actions to be performed before this can be merged

- [ ] Might be a basis for #19 

# Security Measures

None were necessary AFAIK.

# Potential Issues/Future considerations

There is a specific way to bump versions for minor (0.0.1 -> 0.1.0) and major (0.0.1 -> 1.0.0) releases. More info here: [https://github.com/marketplace/actions/github-tag#bumping](https://github.com/marketplace/actions/github-tag#bumping). 

# Additional Info

Ladies and gents, next stop, the moon.  🚀🚀

2021-03-11 07:45 UTC, keebrev requested changes

2021-03-11 07:45 UTC, keebrev commented on .github/workflows/Docs Deployment Pipeline.yml
> -      - run: mkdocs gh-deploy --force
Can I ask why you deleted the documentation pipeline?

2021-03-11 07:45 UTC, keebrev commented on .github/workflows/deploy_to_stable.yml
> +      -
Are you using the 'version' as well when publishing to Docker Hub?

2021-03-11 08:59 UTC, WillemGerritzen commented on .github/workflows/Docs Deployment Pipeline.yml
> -      - run: mkdocs gh-deploy --force
That was a mistake, I thought it was something else.

2021-03-11 12:21 UTC, keebrev approved these changes

2021-03-12 06:54 UTC, dema-trading-ai approved these changes

2021-03-12 06:54 UTC, dema-trading-ai approved these changes

2021-03-12 06:54 UTC, merged